# ChittyConnect Configuration for chittyregistry
service:
  name: chittyregistry
  display_name: Chittyregistry
  type: service
  tier: 2
  organization: CHITTYOS
  chitty_id: ${CHITTYREGISTRY_SERVICE_ID}
  domains:
    production: registry.chitty.cc

onboarding:
  endpoint: https://get.chitty.cc/api/onboard
  provisions: [chitty_id, service_token, certificate, trust_chain]

auth:
  provider: chittyauth
  endpoint: https://auth.chitty.cc
  service_token:
    source: chittyconnect
    key: CHITTYREGISTRY_SERVICE_TOKEN

secrets:
  provider: chittyconnect
  vault: 1password
  paths:
    production: op://ChittyOS/chittyregistry-prod

github:
  repository: CHITTYOS/chittyregistry

monitoring:
  health:
    endpoint: /health
    interval: 60s
