#!/usr/bin/env bash
# Throttled submission of CF inventory stubs to the chittyregistry Gatekeeper.
# Per-request 30s delay to stay under register.chitty.cc rate limit.
# Reads stubs from /tmp/registry-stubs/ generated by registry-probe-services.sh.
#
# Auth: requires CHITTY_MCP_BEARER_TOKEN (or any chitty-prefixed bearer) in env.
# Endpoint: https://register.chitty.cc/api/v1/register (Gatekeeper)
#
# Usage:
#   ./registry-backfill-submit.sh                 # submit all stubs, 30s apart
#   ./registry-backfill-submit.sh --delay 60      # custom delay
#   ./registry-backfill-submit.sh --dry-run       # show payloads, don't submit

set -euo pipefail

STUB_DIR="${STUB_DIR:-/tmp/registry-stubs}"
DELAY=30
DRY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --delay) DELAY="$2"; shift 2 ;;
    --dry-run) DRY="true"; shift ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

: "${CHITTY_MCP_BEARER_TOKEN:?CHITTY_MCP_BEARER_TOKEN required (or any chitty-prefixed bearer)}"
[[ -d "$STUB_DIR" ]] || { echo "Stub dir not found: $STUB_DIR — run registry-probe-services.sh first" >&2; exit 1; }

stubs=("$STUB_DIR"/*.json)
echo "Stubs: ${#stubs[@]}  Delay: ${DELAY}s  Endpoint: register.chitty.cc/api/v1/register"
echo

ok=0; err=0; rate=0
for stub in "${stubs[@]}"; do
  name=$(jq -r .name "$stub")
  host=$(jq -r .hostname "$stub")
  payload=$(jq --arg d "ChittyOS service ${name} hosted at ${host}" '
    .description = $d
    | .metadata.maintainer = "nick@chittycorp.com"
    | .schema = {version: "1.0.0", entities: [], relationships: []}
    | .security = {auth_required: true, scopes: ["chitty:service:read"]}
    | .endpoints = {health: "/health", status: "/api/v1/status"}
  ' "$stub")

  if [[ -n "$DRY" ]]; then
    echo "DRY $name  →  $(echo "$payload" | jq -c '{name,description,version}')"
    continue
  fi

  result=$(curl -sS -X POST "https://register.chitty.cc/api/v1/register" \
    -H "Authorization: Bearer ${CHITTY_MCP_BEARER_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "$payload")

  status=$(echo "$result" | jq -r '.success // false')
  err_msg=$(echo "$result" | jq -r '.error // empty')

  if [[ "$status" == "true" ]]; then
    ok=$((ok+1))
    printf "  OK   %-30s\n" "$name"
  elif [[ "$err_msg" == "rate_limit_exceeded" ]]; then
    retry=$(echo "$result" | jq -r '.retry_after_seconds // 0')
    rate=$((rate+1))
    printf "  RATE %-30s retry_after=%ss — sleeping then retrying\n" "$name" "$retry"
    sleep "$retry"
    # one retry
    result=$(curl -sS -X POST "https://register.chitty.cc/api/v1/register" \
      -H "Authorization: Bearer ${CHITTY_MCP_BEARER_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "$payload")
    if echo "$result" | jq -e '.success' >/dev/null 2>&1; then
      ok=$((ok+1)); printf "  OK   %-30s (after rate sleep)\n" "$name"
    else
      err=$((err+1)); printf "  ERR  %-30s %s\n" "$name" "$(echo "$result" | jq -c .)"
    fi
  else
    err=$((err+1))
    printf "  ERR  %-30s %s\n" "$name" "$(echo "$result" | jq -c .)"
  fi
  sleep "$DELAY"
done

echo
echo "Summary: OK=$ok  ERR=$err  RATE_LIMITED=$rate"
